name: Create Lambda Function

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions tab

jobs:
  create-lambda:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # Change region if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies and Package Code
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -t package
          cp -r app package/app

      - name: Zip Lambda Package
        run: |
          cd package
          zip -r ../lambda_function.zip .

      - name: Create Lambda Function
        run: |
          aws lambda create-function \
            --function-name myai-api \
            --runtime python3.10 \
            --role arn:aws:iam::061051221530:role/AWSlambda \
            --handler app.main.handler \
            --zip-file fileb://lambda_function.zip \
            --timeout 30 \
            --memory-size 256
