name: Deploy FastAPI to AWS Lambda

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt -t package
          cp -r app package/app

      - name: Zip Lambda Package
        run: |
          cd package
          zip -r ../lambda_function.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if needed

      - name: Update AWS Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name myai-api \
            --zip-file fileb://lambda_function.zip
